name: Deploy Halo and PostgreSQL

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Start PostgreSQL container
        run: |
          docker run -d \
            --name postgres-server \
            -e POSTGRES_USER=halo_user \
            -e POSTGRES_PASSWORD=halo_password \
            -e POSTGRES_DB=halo_db \
            -p 5432:5432 \
            postgres:14

      - name: Wait for PostgreSQL to start
        run: |
          until docker exec postgres-server pg_isready -h 127.0.0.1 -p 5432 -U halo_user; do
            echo "Waiting for PostgreSQL to start..."
            sleep 1
          done
          echo "PostgreSQL is up and running!"

      - name: Start Halo container
        run: |
          docker run -it -d \
            --name halo \
            -p 8090:8090 \
            -v ~/.halo2:/root/.halo2 \
            -e JVM_OPTS="-Xmx256m -Xms256m" \
            -e spring.r2dbc.url=r2dbc:postgresql://127.0.0.1:5432/halo_db \
            -e spring.r2dbc.username=halo_user \
            -e spring.r2dbc.password=halo_password \
            -e spring.sql.init.platform=postgresql \
            -e halo.external-url=http://localhost:8090 \
            registry.fit2cloud.com/halo/halo:2.20

      - name: Check container status
        run: |
          sleep 10
          docker ps -a

      - name: Set up Node.js (localtunnel 需要 Node.js 14+)
        uses: actions/setup-node@v3
        with:
          node-version: 18  # 推荐使用 LTS 版本

      - name: Install localtunnel
        run: npm install -g localtunnel  # 全局安装，简单可靠

      - name: Expose 8090 port with localtunnel
        run: |
          # 启动 localtunnel（后台运行，不阻塞）
          lt --port 8090 &
          LT_PID=$!  # 获取 localtunnel 进程 ID
      
          # 等待隧道建立（约 5-10 秒）
          sleep 10
      
          # 获取隧道密码（公网 IP）
          TUNNEL_PASSWORD=$(curl -s https://loca.lt/mytunnelpassword)
          
          # 输出密码到日志（关键步骤）
          echo "======================"
          echo "隧道密码：$TUNNEL_PASSWORD"
          echo "请将此密码告知访问者！"
          echo "======================"
      
          # 保持进程运行（防止工作流提前结束）
          wait $LT_PID  # 等待 localtunnel 进程结束（手动终止或超时）
