name: Deploy Halo with PostgreSQL and PageKite

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 启动 PostgreSQL 容器（保持不变）
      - name: Start PostgreSQL container
        run: |
          docker run -d \
            --name postgres-server \
            -e POSTGRES_USER=halo_user \
            -e POSTGRES_PASSWORD=halo_password \
            -e POSTGRES_DB=halo_db \
            -p 5432:5432 \
            postgres:14

      - name: Wait for PostgreSQL to start
        run: |
          until docker exec postgres-server pg_isready -h 127.0.0.1 -p 5432 -U halo_user; do
            echo "Waiting for PostgreSQL to start..."
            sleep 1
          done
          echo "PostgreSQL is up and running!"

      # 启动 Halo 容器（连接 PostgreSQL 配置）
      - name: Start Halo container (PostgreSQL 配置)
        run: |
          docker run -d \
            --name halo \
            -p 8090:8090 \
            -v ~/.halo2:/root/.halo2 \
            -e JVM_OPTS="-Xmx256m -Xms256m" \
            -e spring.r2dbc.url=r2dbc:postgresql://127.0.0.1:5432/halo_db \
            -e spring.r2dbc.username=halo_user \
            -e spring.r2dbc.password=halo_password \
            -e spring.sql.init.platform=postgresql \
            -e halo.external-url=http://localhost:8090 \
            registry.fit2cloud.com/halo/halo:2.20

      # 安装 PageKite（通过 pip 安装，解决依赖问题）
      - name: Install Pyth
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip  # 安装 Python 和 pip

      # 启动 PageKite 映射 8090 端口（需替换你的 PageKite 域名）
      - name: Expose Halo with PageKite
        run: |
          nohup ssh -R ywzm:80:localhost:8090 serveo.net $
          PAGEKITE_PID=$!
          
          # 等待隧道建立
          sleep 20
          
          # 输出公网访问地址
          echo "======================"
          echo "Halo 公网访问地址: http://$KITE_DOMAIN"
          echo "（PageKite 免费版可能显示随机域名，需在官网注册获取固定域名）"
          echo "======================"
          
          # 保持进程运行（防止工作流提前结束）
          wait $PAGEKITE_PID
