name: Expose Service with Pagekite

on:
  push:
    branches:
      - main

jobs:
  expose-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Pagekite
        run: |
          sudo apt-get update
          sudo apt-get install -y pagekite

      - name: Start your service (e.g., Halo)
        run: |
          docker run -it -d --name halo -p 8090:8090 -v ~/.halo2:/root/.halo2 -e JVM_OPTS="-Xmx256m -Xms256m" registry.fit2cloud.com/halo/halo:2.20

      - name: Expose service with Pagekite
        run: |
          sleep 10
          pagekite.py 8090 yourkite.pagekite.me
